//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tour_Company.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getNumberTour", ReplyAction="http://tempuri.org/IService1/getNumberTourResponse")]
        string getNumberTour(string idCompany);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/numberTourVerified", ReplyAction="http://tempuri.org/IService1/numberTourVerifiedResponse")]
        string numberTourVerified(string idCompany);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/totalCost", ReplyAction="http://tempuri.org/IService1/totalCostResponse")]
        string totalCost(string idTour);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getDepartDate", ReplyAction="http://tempuri.org/IService1/getDepartDateResponse")]
        string getDepartDate(string idTour);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getDepartPosition", ReplyAction="http://tempuri.org/IService1/getDepartPositionResponse")]
        string getDepartPosition(string idTour);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/changePass", ReplyAction="http://tempuri.org/IService1/changePassResponse")]
        void changePass(string idCompany, string newPass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/hasPaid", ReplyAction="http://tempuri.org/IService1/hasPaidResponse")]
        void hasPaid(string idBooking, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/checkVerifyTour", ReplyAction="http://tempuri.org/IService1/checkVerifyTourResponse")]
        string checkVerifyTour(string idTour);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/updateTour", ReplyAction="http://tempuri.org/IService1/updateTourResponse")]
        void updateTour(string idTour, string nameTour, string desc, string imgTour, string price, string duration, string orderQuatity, string departPosition, string departDate, string idZone, string transMethod, string emailAcc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getCustomer", ReplyAction="http://tempuri.org/IService1/getCustomerResponse")]
        System.Data.DataSet getCustomer(string idCompany);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/findCustomer", ReplyAction="http://tempuri.org/IService1/findCustomerResponse")]
        System.Data.DataSet findCustomer(string name, string idCompany);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getNumberCus", ReplyAction="http://tempuri.org/IService1/getNumberCusResponse")]
        string getNumberCus(string idCompay);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/thongKeTour", ReplyAction="http://tempuri.org/IService1/thongKeTourResponse")]
        System.Data.DataSet thongKeTour(string idCompany);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/totalOrder", ReplyAction="http://tempuri.org/IService1/totalOrderResponse")]
        string totalOrder(string idCompany);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/totalCostCompany", ReplyAction="http://tempuri.org/IService1/totalCostCompanyResponse")]
        string totalCostCompany(string idCompany);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/checkLogin", ReplyAction="http://tempuri.org/IService1/checkLoginResponse")]
        bool checkLogin(string user, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/updateComInfo", ReplyAction="http://tempuri.org/IService1/updateComInfoResponse")]
        void updateComInfo(string idCompany, string address, string phone, string email, string web);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getIDCompany", ReplyAction="http://tempuri.org/IService1/getIDCompanyResponse")]
        string getIDCompany(string idCompany);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getCompanyName", ReplyAction="http://tempuri.org/IService1/getCompanyNameResponse")]
        string getCompanyName(string idCompany);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getLegalRep", ReplyAction="http://tempuri.org/IService1/getLegalRepResponse")]
        string getLegalRep(string idCompany);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getTransName", ReplyAction="http://tempuri.org/IService1/getTransNameResponse")]
        string getTransName(string idCompany);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getTaxCode", ReplyAction="http://tempuri.org/IService1/getTaxCodeResponse")]
        string getTaxCode(string idCompany);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getBusiLicense", ReplyAction="http://tempuri.org/IService1/getBusiLicenseResponse")]
        string getBusiLicense(string idCompany);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getCerDate", ReplyAction="http://tempuri.org/IService1/getCerDateResponse")]
        string getCerDate(string idCompany);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAddress", ReplyAction="http://tempuri.org/IService1/getAddressResponse")]
        string getAddress(string idCompany);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getPhone", ReplyAction="http://tempuri.org/IService1/getPhoneResponse")]
        string getPhone(string idCompany);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getEmail", ReplyAction="http://tempuri.org/IService1/getEmailResponse")]
        string getEmail(string idCompany);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getWeb", ReplyAction="http://tempuri.org/IService1/getWebResponse")]
        string getWeb(string idCompany);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getPassCompany", ReplyAction="http://tempuri.org/IService1/getPassCompanyResponse")]
        string getPassCompany(string idCompany);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getData", ReplyAction="http://tempuri.org/IService1/getDataResponse")]
        System.Data.DataSet getData(string table);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/get1Data", ReplyAction="http://tempuri.org/IService1/get1DataResponse")]
        string get1Data(string idCompany, string field);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getTourDetail", ReplyAction="http://tempuri.org/IService1/getTourDetailResponse")]
        string getTourDetail(string idTour);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/demo", ReplyAction="http://tempuri.org/IService1/demoResponse")]
        void demo(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/postTour", ReplyAction="http://tempuri.org/IService1/postTourResponse")]
        void postTour(string nameTour, string description, string idCompany, string imageTour, string priceTour, string duration, string orderQuantity, string departPosition, string departDate, string idZone, string transMethod, string emailNganLuong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getCusInfo", ReplyAction="http://tempuri.org/IService1/getCusInfoResponse")]
        string getCusInfo(string idcCompany, string identifyCard);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getTour", ReplyAction="http://tempuri.org/IService1/getTourResponse")]
        string getTour(string idcCompany, string idTour);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/requestAndResponse", ReplyAction="http://tempuri.org/IService1/requestAndResponseResponse")]
        string requestAndResponse(string idCompany, string title, string Content);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/modifyTourInfo", ReplyAction="http://tempuri.org/IService1/modifyTourInfoResponse")]
        void modifyTourInfo(
                    string idTour, 
                    string nameTour, 
                    string description, 
                    string idCompany, 
                    string imageTour, 
                    string priceTour, 
                    string expiredDate, 
                    string duration, 
                    int orderQuantity, 
                    string departPosition, 
                    string departDate, 
                    string dayUpdate, 
                    string idCity, 
                    string TransMethod, 
                    string userName, 
                    string verify);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/changeInfo", ReplyAction="http://tempuri.org/IService1/changeInfoResponse")]
        void changeInfo(string idCompany, string companyName, string legalRepresentative, string transactionName, string taxCode, string businessLience, string certifiedDate, string address, string phoneNumber, string email, string passWord, string webAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAllTour", ReplyAction="http://tempuri.org/IService1/getAllTourResponse")]
        System.Data.DataSet getAllTour(string idCompany);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getContentTour", ReplyAction="http://tempuri.org/IService1/getContentTourResponse")]
        string getContentTour(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getZone", ReplyAction="http://tempuri.org/IService1/getZoneResponse")]
        System.Data.DataSet getZone();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getBooking", ReplyAction="http://tempuri.org/IService1/getBookingResponse")]
        System.Data.DataSet getBooking(string idTour);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getTickets", ReplyAction="http://tempuri.org/IService1/getTicketsResponse")]
        string getTickets(string idTour);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Tour_Company.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Tour_Company.ServiceReference1.IService1>, Tour_Company.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getNumberTour(string idCompany) {
            return base.Channel.getNumberTour(idCompany);
        }
        
        public string numberTourVerified(string idCompany) {
            return base.Channel.numberTourVerified(idCompany);
        }
        
        public string totalCost(string idTour) {
            return base.Channel.totalCost(idTour);
        }
        
        public string getDepartDate(string idTour) {
            return base.Channel.getDepartDate(idTour);
        }
        
        public string getDepartPosition(string idTour) {
            return base.Channel.getDepartPosition(idTour);
        }
        
        public void changePass(string idCompany, string newPass) {
            base.Channel.changePass(idCompany, newPass);
        }
        
        public void hasPaid(string idBooking, string status) {
            base.Channel.hasPaid(idBooking, status);
        }
        
        public string checkVerifyTour(string idTour) {
            return base.Channel.checkVerifyTour(idTour);
        }
        
        public void updateTour(string idTour, string nameTour, string desc, string imgTour, string price, string duration, string orderQuatity, string departPosition, string departDate, string idZone, string transMethod, string emailAcc) {
            base.Channel.updateTour(idTour, nameTour, desc, imgTour, price, duration, orderQuatity, departPosition, departDate, idZone, transMethod, emailAcc);
        }
        
        public System.Data.DataSet getCustomer(string idCompany) {
            return base.Channel.getCustomer(idCompany);
        }
        
        public System.Data.DataSet findCustomer(string name, string idCompany) {
            return base.Channel.findCustomer(name, idCompany);
        }
        
        public string getNumberCus(string idCompay) {
            return base.Channel.getNumberCus(idCompay);
        }
        
        public System.Data.DataSet thongKeTour(string idCompany) {
            return base.Channel.thongKeTour(idCompany);
        }
        
        public string totalOrder(string idCompany) {
            return base.Channel.totalOrder(idCompany);
        }
        
        public string totalCostCompany(string idCompany) {
            return base.Channel.totalCostCompany(idCompany);
        }
        
        public bool checkLogin(string user, string pass) {
            return base.Channel.checkLogin(user, pass);
        }
        
        public void updateComInfo(string idCompany, string address, string phone, string email, string web) {
            base.Channel.updateComInfo(idCompany, address, phone, email, web);
        }
        
        public string getIDCompany(string idCompany) {
            return base.Channel.getIDCompany(idCompany);
        }
        
        public string getCompanyName(string idCompany) {
            return base.Channel.getCompanyName(idCompany);
        }
        
        public string getLegalRep(string idCompany) {
            return base.Channel.getLegalRep(idCompany);
        }
        
        public string getTransName(string idCompany) {
            return base.Channel.getTransName(idCompany);
        }
        
        public string getTaxCode(string idCompany) {
            return base.Channel.getTaxCode(idCompany);
        }
        
        public string getBusiLicense(string idCompany) {
            return base.Channel.getBusiLicense(idCompany);
        }
        
        public string getCerDate(string idCompany) {
            return base.Channel.getCerDate(idCompany);
        }
        
        public string getAddress(string idCompany) {
            return base.Channel.getAddress(idCompany);
        }
        
        public string getPhone(string idCompany) {
            return base.Channel.getPhone(idCompany);
        }
        
        public string getEmail(string idCompany) {
            return base.Channel.getEmail(idCompany);
        }
        
        public string getWeb(string idCompany) {
            return base.Channel.getWeb(idCompany);
        }
        
        public string getPassCompany(string idCompany) {
            return base.Channel.getPassCompany(idCompany);
        }
        
        public System.Data.DataSet getData(string table) {
            return base.Channel.getData(table);
        }
        
        public string get1Data(string idCompany, string field) {
            return base.Channel.get1Data(idCompany, field);
        }
        
        public string getTourDetail(string idTour) {
            return base.Channel.getTourDetail(idTour);
        }
        
        public void demo(string name) {
            base.Channel.demo(name);
        }
        
        public void postTour(string nameTour, string description, string idCompany, string imageTour, string priceTour, string duration, string orderQuantity, string departPosition, string departDate, string idZone, string transMethod, string emailNganLuong) {
            base.Channel.postTour(nameTour, description, idCompany, imageTour, priceTour, duration, orderQuantity, departPosition, departDate, idZone, transMethod, emailNganLuong);
        }
        
        public string getCusInfo(string idcCompany, string identifyCard) {
            return base.Channel.getCusInfo(idcCompany, identifyCard);
        }
        
        public string getTour(string idcCompany, string idTour) {
            return base.Channel.getTour(idcCompany, idTour);
        }
        
        public string requestAndResponse(string idCompany, string title, string Content) {
            return base.Channel.requestAndResponse(idCompany, title, Content);
        }
        
        public void modifyTourInfo(
                    string idTour, 
                    string nameTour, 
                    string description, 
                    string idCompany, 
                    string imageTour, 
                    string priceTour, 
                    string expiredDate, 
                    string duration, 
                    int orderQuantity, 
                    string departPosition, 
                    string departDate, 
                    string dayUpdate, 
                    string idCity, 
                    string TransMethod, 
                    string userName, 
                    string verify) {
            base.Channel.modifyTourInfo(idTour, nameTour, description, idCompany, imageTour, priceTour, expiredDate, duration, orderQuantity, departPosition, departDate, dayUpdate, idCity, TransMethod, userName, verify);
        }
        
        public void changeInfo(string idCompany, string companyName, string legalRepresentative, string transactionName, string taxCode, string businessLience, string certifiedDate, string address, string phoneNumber, string email, string passWord, string webAddress) {
            base.Channel.changeInfo(idCompany, companyName, legalRepresentative, transactionName, taxCode, businessLience, certifiedDate, address, phoneNumber, email, passWord, webAddress);
        }
        
        public System.Data.DataSet getAllTour(string idCompany) {
            return base.Channel.getAllTour(idCompany);
        }
        
        public string getContentTour(string id) {
            return base.Channel.getContentTour(id);
        }
        
        public System.Data.DataSet getZone() {
            return base.Channel.getZone();
        }
        
        public System.Data.DataSet getBooking(string idTour) {
            return base.Channel.getBooking(idTour);
        }
        
        public string getTickets(string idTour) {
            return base.Channel.getTickets(idTour);
        }
    }
}
